project_id = "guxldhjlujwafmxwjkae"

[functions]
  [functions.admissions]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.delete-demo-data]
    verify_jwt = false
  [functions.invite-user]
    verify_jwt = false
  [functions.start-demo]
    verify_jwt = false
