import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "dist",
      "coverage",
      "playwright-report",
      // Generated by Supabase/Lovable and overwritten on every sync.
      "src/integrations/supabase/types.ts",
      "src/integrations/supabase/previewAuthStorage.ts",
      // Lovable's branded-email scaffolding. The hook and its React Email
      // templates are regenerated wholesale every time the email setup is
      // touched in Lovable, so hand-fixing their `any`s just means CI goes red
      // again on the next sync — previewAuthStorage.ts above was rewritten five
      // times before it was listed here.
      "supabase/functions/auth-email-hook/**",
      "supabase/functions/_shared/email-templates/**",
      // Vendored shadcn/ui chart wrapper; its `any`s come from Recharts'
      // untyped tooltip payloads and would return on any component update.
      "src/components/ui/chart.tsx",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      // On (as a warning) so dead code and unused imports stay visible.
      // Underscore-prefixed names are the opt-out.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
      // An error again. Every remaining `any` was removed by typing the query
      // results properly rather than by silencing the rule, and tsconfig.app.json
      // sets noImplicitAny so a deleted annotation cannot quietly become one.
      "@typescript-eslint/no-explicit-any": "error",
    },
  },
  {
    // Edge functions run on Deno, not in the browser.
    files: ["supabase/functions/**/*.ts"],
    languageOptions: {
      globals: { Deno: "readonly" },
    },
  },
);
