ALTER TABLE public.payroll_runs
  ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS submitted_by UUID,
  ADD COLUMN IF NOT EXISTS paid_at TIMESTAMP WITH TIME ZONE;